// <auto-generated />
namespace Apartments__MVC_Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dataAnotetionsToApartment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataAnotetionsToApartment));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021804081_dataAnotetionsToApartment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
